### PR TITLE
Add block state IDs to all versions with block data

### PR DESCRIPTION
**Pull request by extremeheat**

### CODE REVIEW

**Comment by rom1504** [comment]
Why ? This will be confusing as old versions don't have state ids

**Comment by extremeheat** [comment]
Yes, but I think this makes the API more consistent across all versions. Block state IDs aren’t a hard coded list but something the vanilla game also internally assigns iteratively from the internal block registry.

I think the only time you need to worry about this is to check whether a block has properties attached to it, if all versions have properties there’s no need for a special check. When runtime computed block states get added (eg, for fences <1.13 or on bedrock) then it’s as simple adding in extra state information from the chunk/world implementation

**Comment by extremeheat** [comment]
Pretty sure this is also how most codebases implemented the change during the flattening, via code search:

* https://github.com/MCCTeam/Minecraft-Console-Client/blob/698690293809dec8ce3ff0c96d8566d4fd8d160a/MinecraftClient/Mapping/Block.cs#L46
* https://github.com/NiclasOlofsson/MiNET/blob/f7fb319daf5b2c8e1e0c90e58adecbb8e024992a/src/MiNET/MiNET/Blocks/BlockFactory.cs#L198
* https://github.com/Pokechu22/WorldDownloader/blob/c7e1d2600f0d39825446103923a67d11b8c0c6e1/share/src/main/java/wdl/SanityCheck.java#L105
* https://github.com/ammaraskar/pyCraft/blob/bcd156e83bd35fb2fdc6cfa64f97bfc96d7cc1a1/minecraft/networking/packets/clientbound/play/block_change_packet.py#L33
* https://github.com/webbukkit/dynmap/blob/b3de1dafe309475bdbdb471f2cd4c661a8d20935/bukkit-helper/src/main/java/org/dynmap/bukkit/helper/BukkitVersionHelper.java#L169
..

The approach here works bidirectionally as metadata only can go up to 0b1111, and the assumption is made that all the metadata states are valid

**Comment by rom1504** [comment]
Let's go with that for now but I think it will be better directly in minecraft data. Can be done in future changes

**Pull request merged**
