### PR TITLE
include blocksB2J and blocksJ2B if available

### PR DESCRIPTION
**Pull request by Sertonix**

### CODE REVIEW

**Comment by extremeheat** [comment]
This should be exposed indeed, however schema may also need to change per mcdata PR https://github.com/PrismarineJS/minecraft-data/pull/532

**Comment by Sertonix** [comment]
Yes thats why I closed it

**Comment by rom1504** [comment]
will you finish this ?

**Comment by rom1504** [comment]
old, re-open if you want to finish

**Pull request closed without merging**
