### PR TITLE
Remove findItemOrBlockById and findItemOrBlockByName

### PR DESCRIPTION
**Pull request by amoraschi**
- Remove them from the code
- Remove them from the typings

Closes Issue 179 partially

### CODE REVIEW

**Comment by rom1504** [comment]
Thanks, can you open a PR for version 3.0.0 in mc data directly (to keep the version sync) ?

**Comment by amoraschi** [comment]
> Thanks, can you open a PR for version 3.0.0 in mc data directly (to keep the version sync) ?

Done
https://github.com/PrismarineJS/node-minecraft-data/pull/187

**Comment by nstringham** [comment]
is there a reason these where removed? and is there a recommendation for anyone who was using them?

**Comment by u9g** [comment]
> is there a reason these where removed? and is there a recommendation for anyone who was using them?

items and blocks have different ids now, use their respective indexers, 
```js
mcData.itemsByName['stone']
mcData.blocksByName['stone']
```

**Comment by nstringham** [comment]
> > is there a reason these where removed? and is there a recommendation for anyone who was using them?
> 
> items and blocks have different ids now, use their respective indexers,
> 
> ```js
> mcData.itemsByName['stone']
> mcData.blocksByName['stone']
> ```

thank you :)

**Pull request merged**
