### PR TITLE
Add more version comparisons

### PR DESCRIPTION
**Pull request by Eejit43**
This PR adds more version comparison directly to the `minecraftData` object (`isOlderThan`, etc.)

### CODE REVIEW

**Comment by Eejit43** [comment]
> Why?

Because it exists for `isNewerOrEqualTo` and `isOlderThan` already, so why not have it available for all of them

**Comment by Eejit43** [comment]
> Why?

I'd propose either merging this *or* removing those methods as they are just duplicates. Seems like they were created simply for tests. Personally just bugs me that those two exist, but if you'd rather just leave them be that's fine

**Comment by Eejit43** [comment]
> The 2 existing methods are sufficient for all comparison. What would adding many more methods or removing these 2 bring ?

They are just duplicate methods, I don't see the harm in switching the test usages of them (and deleting those two methods)

**Comment by rom1504** [comment]
It's a breaking change and apparently there is no reason to do it

**Comment by Eejit43** [comment]
> It's a breaking change and apparently there is no reason to do it

Ok fine with me

**Pull request closed without merging**
