### PR TITLE
Refactor generate_data.js

### PR DESCRIPTION
**Pull request by Saiv46**
Also re-implements #42

### CODE REVIEW

**Comment by KaffinPX** [comment]
Lowers ram usage 15 MB~ its a huge difference i think.

**Comment by extremeheat** [comment]
The only place this is an issue is a big issue is prismarine-web-client I think. I just looked at memory usage, and you're right it seems like there is a considerable amount of memory used (~30MB saved by loading just one version), but it doesn't come from the JSON, it's the indexers that add the extra memory.

```js
{ # 3 versions
  rss: 29425664, // 29 MB
  heapTotal: 9281536,
  heapUsed: 8590056,
  external: 424167,
  arrayBuffers: 18102
}
```

```js
{ # All versions
  rss: 68833280, // 68 MB
  heapTotal: 58286080,
  heapUsed: 29196496,
  external: 5544817,
  arrayBuffers: 277877
}
```

I'm not a fan of the Proxy solution, that feels like a hack and it doesn't fix the issue for pwc, the biggest place for concern. I think this is something that should be fixed by a broader refactor to only load and index versions that are actually used.

**Comment by KaffinPX** [comment]
> The only place this is an issue is a big issue is prismarine-web-client I think. I just looked at memory usage, and you're right it seems like there is a considerable amount of memory used (~40MB saved by loading just one version), but it doesn't come from the JSON, it's the indexers that add the extra memory.
> 
> ```js
> { # 1 version
>   rss: 28618752, // 28 MB
>   heapTotal: 9281536,
>   heapUsed: 8590056,
>   external: 424167,
>   arrayBuffers: 18102
> }
> ```
> 
> ```js
> { # All versions
>   rss: 68833280, // 68 MB
>   heapTotal: 58286080,
>   heapUsed: 29196496,
>   external: 5544817,
>   arrayBuffers: 277877
> }
> ```
> 
> I'm not a fan of the Proxy solution, that feels like a hack and it doesn't fix the issue for pwc, the biggest place for concern. I think this is something that should be fixed by a broader refactor to only load and index versions that are actually used.

Is it working with prismarine-viewer? Do u tried yet?

**Comment by extremeheat** [comment]
I'm mistaken, it's not the indexer, node just tries to load everything since it's all exported in the data.js module. Your solution works in node, but it I don't think it would work on webpack. Once bundled, all the `require` functions get turned into `__webpack_require__` functions that use IDs, not strings to reference modules. Those IDs are generated at runtime. Try something like 

```js
let blocks, blockCollisionShapes, biomes
switch (version) {
  case '1.16.4':
    blocks = require('1.16.4/blocks.json')
    blockCollisionShapes = require('1.16.4/collisions.json')
  case '1.17': {
     ....
  }
}
```

**Comment by KaffinPX** [comment]
> I'm mistaken, it's not the indexer, node just tries to load everything since it's all exported in the data.js module. Your solution works in node, but it I don't think it would work on webpack. Once bundled, all the `require` functions get turned into `__webpack_require__` functions that use IDs, not strings to reference modules. Those IDs are generated at runtime. Try something like
> 
> ```js
> let blocks, blockCollisionShapes, biomes
> switch (version) {
>   case '1.16.4':
>     blocks = require('1.16.4/blocks.json')
>     blockCollisionShapes = require('1.16.4/collisions.json')
>   case '1.17': {
>      ....
>   }
> }
> ```

anyway can u try in your free time?

**Comment by Saiv46** [comment]
@extremeheat I tried the switch solution you suggested, here's the results

Branch used | Memory used (all versions) | (one version)
---- | ---- | ----
Master | 48.08 MB | -
#68 (cache clean) | 44.36 MB | -
#83 (switch + inline) | 43.70 MB | 2.38 MB

Snippet for measurement:
```js
// __webpack_import__ = require
a = process.memoryUsage().rss;require('./data.js').pc['1.7'];b = process.memoryUsage().rss;console.log(((b-a)/1e6).toFixed(2), "MB")
```

**Comment by Saiv46** [comment]
Can somebody review it?

**Comment by rom1504** [comment]
`Proxy` usage will break webpack usage of minecraft data which is the main point of this generate data file

**Pull request closed without merging**
