### PR TITLE
Fix `foodsByFoodPoints` and `foodsBySaturation`

### LINKED ISSUE #202: `foodsByFoodPoints` and `foodsBySaturation` incorrect
`foodsByFoodPoints` and `foodsBySaturation` only show a single item with each point/saturation, not all options. 

For example, `foodsByFoodPoints[2]` only returns:
```js
{
  id: 1054,
  name: 'glow_berries',
  stackSize: 64,
  displayName: 'Glow Berries',
  foodPoints: 2,
  saturation: 0.4,
  effectiveQuality: 2.4,
  saturationRatio: 0.2
}
```
not all food with `foodPoints` of 2

### PR DESCRIPTION
**Pull request by Eejit43**
This PR changes `foodsByFoodPoints` and `foodsBySaturation` to return an array of all food with the given foodPoints/saturation (respectively) rather than a single entry.

Closes #202

### CODE REVIEW

**Comment by rom1504** [comment]
Can you update the doc ? Is there any usage of this ? For the example in mineflayer or prismarine packages?

**Comment by Eejit43** [comment]
> Can you update the doc ? Is there any usage of this ? For the example in mineflayer or prismarine packages?

docs are updated in #209 (not here as the format is fully changed). I have no clue what the use purpose is, you'll have to ask whoever implemented it in the first place

**Comment by rom1504** [comment]
> I have no clue what the use purpose is, you'll have to ask whoever implemented it in the first place

This needs to be figured out otherwise it's a breaking change and we need a major version

**Comment by Eejit43** [comment]
> > I have no clue what the use purpose is, you'll have to ask whoever implemented it in the first place
> 
> This needs to be figured out otherwise it's a breaking change and we need a major version

Added in #37 (a PR you approved), authored by `@AppDevMichael`. For usages, I have no clue. I personally cannot think of a use purpose for the methods, but if they are in the package, they should definitely at least work.

**Comment by rom1504** [comment]
https://cs.github.com/?scopeName=All+repos&scope=&q=foodsBySaturation

https://cs.github.com/?q=foodsByFoodPoints

Looks like it's used nowhere.

**Comment by rom1504** [comment]
I think let's just remove it.
Seems very specific, people can implement it for their specific use cases

**Comment by Eejit43** [comment]
> I think let's just remove it. Seems very specific, people can implement it for their specific use cases

Sounds good! I'll close this and make a separate PR to remove it!

**Pull request closed without merging**
