### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by u9g** [comment]
Schedules findItemOrBlockBy(id|name) to be removed by June 1 2022

**Comment by rom1504** [comment]
let's just do April 1

**Comment by rom1504** [comment]
and can you do PRs to stop using that function in mineflayer (and potentially other repos) ?

**Comment by u9g** [comment]
> and can you do PRs to stop using that function in mineflayer (and potentially other repos) ?

yeah

**Pull request merged**
